### ISSUE TITLE
Could not find a version that satisfies the requirement ibm-vpc>=0.5.0

### ISSUE THREAD

**Issue by PankajWorks** [IBM/vpc-python-sdk#18]
Hello,

Am trying to get the sdk installed. Going by the documentation i tried to install the sdk but it fails with error "ERROR: Could not find a version that satisfies the requirement ibm-vpc>=0.5.0 (from versions: 0.0.2, 0.0.3, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1)"

Below  is the error
```bash
pip install --upgrade "ibm-vpc>=0.5.0"                                      
ERROR: Could not find a version that satisfies the requirement ibm-vpc>=0.5.0
ERROR: No matching distribution found for ibm-vpc>=0.5.0
```
It seems the latest version on pypi is "0.4.1"
![image](https://user-images.githubusercontent.com/12717111/114354501-f3ebac00-9b8b-11eb-9318-1a8d6dd8a1f0.png)

**Comment by astha-jain** [comment]
Thank you for reaching out. It should be fixed with https://pypi.org/project/ibm-vpc/
