### ISSUE TITLE
ETA for BMS

### ISSUE THREAD

**Issue by jimccann-rh** [IBM/vpc-python-sdk#34]
Hey was just wondering if there is a ETA on https://cloud.ibm.com/apidocs/vpc?code=python#list-bare-metal-server-profiles. I don't seem to see it in ibm-vpc=0.9.0.

Keep up the good work!

**Comment by astha-jain** [comment]
Thanks for opening the issue. Bare metal support was available in [v0.10.0](https://github.com/IBM/vpc-python-sdk/releases/tag/v0.10.0)
