### ISSUE TITLE
Python SDK installation fails

### ISSUE THREAD

**Issue by AugieMena3** [IBM/vpc-python-sdk#6]
$ sudo pip install --upgrade "ibm-vpc>=0.0.2"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/Users/mena/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ibm-vpc>=0.0.2
  Downloading ibm-vpc-0.0.2.tar.gz (208 kB)
     |████████████████████████████████| 208 kB 3.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-CzYdSz/ibm-vpc/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-CzYdSz/ibm-vpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-GvjW_S
         cwd: /private/tmp/pip-install-CzYdSz/ibm-vpc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-CzYdSz/ibm-vpc/setup.py", line 26, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by astha-jain** [comment]
Fixed
